/// PostgreSQL health check and SSL provisioning (server build only).
///
/// IMPORTANT: actual provisioning (initdb, Windows Service registration,
/// pg_hba.conf hardening, credential generation) happens ONCE, during
/// installation, in the NSIS post-install hook — see
/// `src-tauri/windows/hooks.nsh`. That hook runs with the Administrator
/// privileges the installer already has.
///
/// The running HMS app NEVER requests elevation and never registers or
/// modifies the Windows Service itself. This module only:
///   1. Verifies on each launch that the service is running and healthy.
///   2. On the very first launch after install, enables PostgreSQL's own
///      SSL (two-phase setup — see ensure_postgres_ssl_enabled below).
use std::path::Path;
use std::process::Command;
use std::time::Duration;

const SERVICE_NAME: &str = "HMS-PostgreSQL";

#[derive(Debug, Clone)]
pub struct HealthCheckResult {
    pub service_running: bool,
    pub accepting_connections: bool,
}

/// Checks the PostgreSQL Windows Service is running and the server is
/// accepting connections. Does NOT attempt to install, register, or start
/// anything — if the service isn't there, that means the installer hook
/// didn't run or failed, which the caller should surface as a setup error
/// pointing the person back to re-running the installer.
pub fn check_postgres_health(pg_bin_dir: &Path, port: u16) -> Result<HealthCheckResult, String> {
    let service_running = is_service_running();

    if !service_running {
        return Ok(HealthCheckResult {
            service_running: false,
            accepting_connections: false,
        });
    }

    let accepting_connections = wait_until_accepting_connections(pg_bin_dir, port, 20);

    Ok(HealthCheckResult {
        service_running,
        accepting_connections,
    })
}

fn is_service_running() -> bool {
    let output = Command::new("sc").args(["query", SERVICE_NAME]).output();
    match output {
        Ok(o) => {
            let text = String::from_utf8_lossy(&o.stdout);
            text.contains("RUNNING")
        }
        Err(_) => false,
    }
}

/// Polls pg_isready for up to `max_attempts` * 500ms. If the bundled
/// pg_isready.exe isn't found (e.g. running via `cargo run` in dev without
/// the installer having placed binaries), falls back to a raw TCP check.
fn wait_until_accepting_connections(pg_bin_dir: &Path, port: u16, max_attempts: u32) -> bool {
    let pg_isready = pg_bin_dir.join("pg_isready.exe");

    for _ in 0..max_attempts {
        let ok = if pg_isready.exists() {
            Command::new(&pg_isready)
                .arg("-p")
                .arg(port.to_string())
                .output()
                .map(|o| o.status.success())
                .unwrap_or(false)
        } else {
            crate::discovery::is_reachable("127.0.0.1", port, 500)
        };

        if ok {
            return true;
        }
        std::thread::sleep(Duration::from_millis(500));
    }
    false
}

/// Standard location the installer placed the PostgreSQL binaries —
/// used only for the optional pg_isready health check above, never for
/// provisioning.
pub fn default_pg_bin_dir() -> Option<std::path::PathBuf> {
    let program_data = std::env::var_os("ProgramData")?;
    Some(std::path::PathBuf::from(program_data).join("HMS").join("pgsql").join("bin"))
}

/// Returns true if SSL has already been enabled on this installation.
/// Callers use this to decide whether to connect with sslmode=disable
/// (bootstrap) or sslmode=require (normal).
pub fn is_ssl_already_enabled(pgdata_dir: &Path) -> bool {
    pgdata_dir.join(".hms_ssl_enabled").exists()
}

/// Second phase of provisioning, run by the app itself (not the installer)
/// on first launch, once `tls_provision::ensure_tls_material` has produced
/// a certificate.
///
/// WHY TWO PHASES: The installer hook can't enable Postgres SSL because the
/// self-signed certificate doesn't exist yet at install time — it's
/// generated by rcgen in Rust on first launch. This function bridges that
/// gap: it runs once, connects to Postgres WITHOUT SSL (sslmode=disable,
/// safe because nothing sensitive is sent and pg_hba.conf still uses
/// plain `host` rules at this point), writes the SSL config, upgrades
/// pg_hba.conf to `hostssl`, and restarts the service.
///
/// IDEMPOTENCY / CRASH SAFETY: The marker file is written BEFORE the
/// service restart (not after), so if the app crashes between writing
/// config and restarting, the next launch sees the marker, skips this
/// function, and just calls restart_service() to finish what was started.
/// This prevents the double-append-to-postgresql.conf corruption that
/// would happen if we re-ran the whole function.
///
/// Returns true if SSL was just enabled (caller should re-verify health),
/// false if the marker already existed (nothing was done).
pub fn ensure_postgres_ssl_enabled(pgdata_dir: &Path, cert_path: &Path, key_path: &Path) -> Result<bool, String> {
    let marker = pgdata_dir.join(".hms_ssl_enabled");
    if marker.exists() {
        return Ok(false); // already done on a previous launch, nothing to do
    }

    let conf_path = pgdata_dir.join("postgresql.conf");
    let mut conf = std::fs::read_to_string(&conf_path)
        .map_err(|e| format!("Cannot read postgresql.conf: {}", e))?;

    // Use forward slashes — PostgreSQL on Windows accepts both, and
    // forward slashes avoid any escaping issues in the conf file.
    let cert_str = cert_path.to_string_lossy().replace('\\', "/");
    let key_str = key_path.to_string_lossy().replace('\\', "/");

    conf.push_str(&format!(
        "\n# HMS: TLS enabled on first launch (see tls_provision.rs + pg_provision.rs)\nssl = on\nssl_cert_file = '{}'\nssl_key_file = '{}'\n",
        cert_str, key_str,
    ));
    std::fs::write(&conf_path, conf)
        .map_err(|e| format!("Cannot write postgresql.conf: {}", e))?;

    // Upgrade pg_hba.conf from plain `host` to `hostssl` so plaintext
    // connections are rejected outright once SSL is on. This must happen
    // in the same step so there's no window where SSL is off but the
    // hostssl rules would reject plain connections.
    let hba_path = pgdata_dir.join("pg_hba.conf");
    let hba_rules = "\
# HMS managed rules — local app + LAN clients only, SSL + scram-sha-256 required.\n\
hostssl all             all             127.0.0.1/32            scram-sha-256\n\
hostssl all             all             ::1/128                 scram-sha-256\n\
hostssl all             all             10.0.0.0/8              scram-sha-256\n\
hostssl all             all             172.16.0.0/12           scram-sha-256\n\
hostssl all             all             192.168.0.0/16          scram-sha-256\n";
    std::fs::write(&hba_path, hba_rules)
        .map_err(|e| format!("Cannot write pg_hba.conf: {}", e))?;

    // Restrict private key file permissions (defence in depth — Postgres
    // on Windows doesn't enforce the POSIX 0600 check, but we still do it).
    let _ = Command::new("icacls")
        .arg(key_path)
        .args(["/inheritance:r", "/grant:r", "SYSTEM:F", "/grant:r", "*S-1-5-32-544:F"])
        .output();

    // Write the marker BEFORE the restart. If the app crashes mid-restart,
    // the next launch skips re-writing the config (avoids double-append)
    // and goes straight to the health check, which will either find
    // Postgres running or wait for it to come up. The service restart is
    // idempotent (sc stop on a stopped service is harmless).
    std::fs::write(&marker, "1")
        .map_err(|e| format!("Cannot write SSL marker file: {}", e))?;

    restart_service()?;

    Ok(true)
}

fn restart_service() -> Result<(), String> {
    // Stop — ignore errors (service may already be stopped)
    let _ = Command::new("sc").args(["stop", SERVICE_NAME]).output();

    // Wait for it to fully stop before starting again
    std::thread::sleep(Duration::from_secs(3));

    let start = Command::new("sc")
        .args(["start", SERVICE_NAME])
        .output()
        .map_err(|e| format!("Failed to start service: {}", e))?;

    if !start.status.success() {
        return Err(format!(
            "Failed to restart PostgreSQL after enabling SSL: {}",
            String::from_utf8_lossy(&start.stderr)
        ));
    }

    // Give Postgres time to actually come up before the caller tries to
    // connect. The health check loop in check_postgres_health adds another
    // layer of polling on top of this initial sleep.
    std::thread::sleep(Duration::from_secs(4));

    Ok(())
}
